services:
  - type: web
    name: tiikii-festival-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /opt/render/project/src/database/tiikii_festival.db
      - key: CLIENT_URL
        value: https://your-frontend-domain.com
